repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # pre-commit-hooks v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        name: Check YAML syntax
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/codespell-project/codespell
    rev: 63c8f8312b7559622c0d82815639671ae42132ac # v2.4.1
    hooks:
      - id: codespell

  - repo: https://github.com/rhysd/actionlint
    rev: 0933c147c9d6587653d45fdcb4c497c57a65f9af # v1.7.10
    hooks:
      - id: actionlint

  - repo: https://github.com/gitleaks/gitleaks
    rev: v5.0.1 # v8.29.1
    hooks:
      - id: gitleaks
